from classes.chu_piece_maker import ChuPieceMaker

def imagefilename(piecename: str, rotate: bool = False, ispromoted: bool = False):
    result = f"{outputpath}{piecename}"

    if piecename.endswith("_sente"):
        pass
    elif piecename.endswith("_gote"):
        pass
    else:
        if rotate:
            result += "_gote"
        else:
            result += "_sente"
    
    if ispromoted:
        result += "_promoted"

    result += ".png"
    return result

def create_piece_size_A_tokinstyle(piecename: str, rotate: bool = False, ispromoted: bool = False):
    mypieceimage = MyChuPieceMaker.create_piece_size_fromjson(piecename=piecename, rotate=rotate, ispromoted=ispromoted, tiletypename="A_tokinstyle")
    MyChuPieceMaker.save_image(mypieceimage, imagefilename(piecename=piecename, rotate=rotate, ispromoted=ispromoted))

def create_piece_size_A(piecename: str, rotate: bool = False, ispromoted: bool = False):
    mypieceimage = MyChuPieceMaker.create_piece_size_fromjson(piecename=piecename, rotate=rotate, ispromoted=ispromoted, tiletypename="A")
    MyChuPieceMaker.save_image(mypieceimage, imagefilename(piecename=piecename, rotate=rotate, ispromoted=ispromoted))

def create_piece_size_B(piecename: str, rotate: bool = False, ispromoted: bool = False):
    mypieceimage = MyChuPieceMaker.create_piece_size_fromjson(piecename=piecename, rotate=rotate, ispromoted=ispromoted, tiletypename="B")
    MyChuPieceMaker.save_image(mypieceimage, imagefilename(piecename=piecename, rotate=rotate, ispromoted=ispromoted))

def create_piece_size_B_plus(piecename: str, rotate: bool = False, ispromoted: bool = False):
    mypieceimage = MyChuPieceMaker.create_piece_size_fromjson(piecename=piecename, rotate=rotate, ispromoted=ispromoted, tiletypename="B_plus")
    MyChuPieceMaker.save_image(mypieceimage, imagefilename(piecename=piecename, rotate=rotate, ispromoted=ispromoted))

def create_piece_size_C(piecename: str, rotate: bool = False, ispromoted: bool = False):
    mypieceimage = MyChuPieceMaker.create_piece_size_fromjson(piecename=piecename, rotate=rotate, ispromoted=ispromoted, tiletypename="C")
    MyChuPieceMaker.save_image(mypieceimage, imagefilename(piecename=piecename, rotate=rotate, ispromoted=ispromoted))

def create_piece_size_D(piecename: str, rotate: bool = False, ispromoted: bool = False):
    mypieceimage = MyChuPieceMaker.create_piece_size_fromjson(piecename=piecename, rotate=rotate, ispromoted=ispromoted, tiletypename="D")
    MyChuPieceMaker.save_image(mypieceimage, imagefilename(piecename=piecename, rotate=rotate, ispromoted=ispromoted))



def add_for_taikyoku():
    #PLS NOTE vast majority of these pieces is also a potentially promoted piece!
    create_piece_size_C(piecename="rear_standard")
    create_piece_size_C(piecename="rear_standard", rotate=True)
    create_piece_size_C(piecename="rear_standard", ispromoted=True)
    create_piece_size_C(piecename="rear_standard", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="ceramic_dove")
    create_piece_size_C(piecename="ceramic_dove", rotate=True)
    create_piece_size_C(piecename="ceramic_dove", ispromoted=True)
    create_piece_size_C(piecename="ceramic_dove", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="earth_dragon")
    create_piece_size_C(piecename="earth_dragon", rotate=True)
    create_piece_size_C(piecename="earth_dragon", ispromoted=True)
    create_piece_size_C(piecename="earth_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="running_horse")
    create_piece_size_C(piecename="running_horse", rotate=True)
    create_piece_size_C(piecename="running_horse", ispromoted=True)
    create_piece_size_C(piecename="running_horse", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="beast_cadet")
    create_piece_size_C(piecename="beast_cadet", rotate=True)
    create_piece_size_C(piecename="beast_cadet", ispromoted=True)
    create_piece_size_C(piecename="beast_cadet", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="right_mountain_eagle")
    create_piece_size_C(piecename="right_mountain_eagle", rotate=True)
    create_piece_size_C(piecename="right_mountain_eagle", ispromoted=True)
    create_piece_size_C(piecename="right_mountain_eagle", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="left_mountain_eagle")
    create_piece_size_C(piecename="left_mountain_eagle", rotate=True)
    create_piece_size_C(piecename="left_mountain_eagle", ispromoted=True)
    create_piece_size_C(piecename="left_mountain_eagle", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="running_rabbit")
    create_piece_size_C(piecename="running_rabbit", rotate=True)
    create_piece_size_C(piecename="running_rabbit", ispromoted=True)
    create_piece_size_C(piecename="running_rabbit", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="turtle_dove")
    create_piece_size_C(piecename="turtle_dove", rotate=True)
    create_piece_size_C(piecename="turtle_dove", ispromoted=True)
    create_piece_size_C(piecename="turtle_dove", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="flying_swallow")
    create_piece_size_C(piecename="flying_swallow", rotate=True)
    create_piece_size_C(piecename="flying_swallow", ispromoted=True)
    create_piece_size_C(piecename="flying_swallow", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="captive_officer")
    create_piece_size_C(piecename="captive_officer", rotate=True)
    create_piece_size_C(piecename="captive_officer", ispromoted=True)
    create_piece_size_C(piecename="captive_officer", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="rain_dragon")
    create_piece_size_C(piecename="rain_dragon", rotate=True)
    create_piece_size_C(piecename="rain_dragon", ispromoted=True)
    create_piece_size_C(piecename="rain_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="forest_demon")
    create_piece_size_C(piecename="forest_demon", rotate=True)
    create_piece_size_C(piecename="forest_demon", ispromoted=True)
    create_piece_size_C(piecename="forest_demon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="mountain_stag")
    create_piece_size_C(piecename="mountain_stag", rotate=True)
    create_piece_size_C(piecename="mountain_stag", ispromoted=True)
    create_piece_size_C(piecename="mountain_stag", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="running_pup")
    create_piece_size_C(piecename="running_pup", rotate=True)
    create_piece_size_C(piecename="running_pup", ispromoted=True)
    create_piece_size_C(piecename="running_pup", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="running_serpent")
    create_piece_size_C(piecename="running_serpent", rotate=True)
    create_piece_size_C(piecename="running_serpent", ispromoted=True)
    create_piece_size_C(piecename="running_serpent", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="side_serpent")
    create_piece_size_C(piecename="side_serpent", rotate=True)
    create_piece_size_C(piecename="side_serpent", ispromoted=True)
    create_piece_size_C(piecename="side_serpent", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_dove")
    create_piece_size_C(piecename="great_dove", rotate=True)
    create_piece_size_C(piecename="great_dove", ispromoted=True)
    create_piece_size_C(piecename="great_dove", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="running_tiger")
    create_piece_size_C(piecename="running_tiger", rotate=True)
    create_piece_size_C(piecename="running_tiger", ispromoted=True)
    create_piece_size_C(piecename="running_tiger", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="running_bear")
    create_piece_size_C(piecename="running_bear", rotate=True)
    create_piece_size_C(piecename="running_bear", ispromoted=True)
    create_piece_size_C(piecename="running_bear", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="gold_chariot")
    create_piece_size_C(piecename="gold_chariot", rotate=True)
    create_piece_size_C(piecename="gold_chariot", ispromoted=True)
    create_piece_size_C(piecename="gold_chariot", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="running_stag")
    create_piece_size_C(piecename="running_stag", rotate=True)
    create_piece_size_C(piecename="running_stag", ispromoted=True)
    create_piece_size_C(piecename="running_stag", rotate=True, ispromoted=True)
    create_piece_size_B_plus(piecename="running_wolf")
    create_piece_size_B_plus(piecename="running_wolf", rotate=True)
    create_piece_size_B_plus(piecename="running_wolf", ispromoted=True)
    create_piece_size_B_plus(piecename="running_wolf", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="right_tiger")
    create_piece_size_C(piecename="right_tiger", rotate=True)
    create_piece_size_C(piecename="right_tiger", ispromoted=True)
    create_piece_size_C(piecename="right_tiger", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="left_tiger")
    create_piece_size_C(piecename="left_tiger", rotate=True)
    create_piece_size_C(piecename="left_tiger", ispromoted=True)
    create_piece_size_C(piecename="left_tiger", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="right_dragon")
    create_piece_size_C(piecename="right_dragon", rotate=True)
    create_piece_size_C(piecename="right_dragon", ispromoted=True)
    create_piece_size_C(piecename="right_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="left_dragon")
    create_piece_size_C(piecename="left_dragon", rotate=True)
    create_piece_size_C(piecename="left_dragon", ispromoted=True)
    create_piece_size_C(piecename="left_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="beast_officer")
    create_piece_size_C(piecename="beast_officer", rotate=True)
    create_piece_size_C(piecename="beast_officer", ispromoted=True)
    create_piece_size_C(piecename="beast_officer", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="wind_dragon")
    create_piece_size_C(piecename="wind_dragon", rotate=True)
    create_piece_size_C(piecename="wind_dragon", ispromoted=True)
    create_piece_size_C(piecename="wind_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="free_pup")
    create_piece_size_C(piecename="free_pup", rotate=True)
    create_piece_size_C(piecename="free_pup", ispromoted=True)
    create_piece_size_C(piecename="free_pup", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="water_dragon")
    create_piece_size_C(piecename="water_dragon", rotate=True)
    create_piece_size_C(piecename="water_dragon", ispromoted=True)
    create_piece_size_C(piecename="water_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="fire_dragon")
    create_piece_size_C(piecename="fire_dragon", rotate=True)
    create_piece_size_C(piecename="fire_dragon", ispromoted=True)
    create_piece_size_C(piecename="fire_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="phoenix_master")
    create_piece_size_C(piecename="phoenix_master", rotate=True)
    create_piece_size_C(piecename="phoenix_master", ispromoted=True)
    create_piece_size_C(piecename="phoenix_master", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="kirin_master")
    create_piece_size_C(piecename="kirin_master", rotate=True)
    create_piece_size_C(piecename="kirin_master", ispromoted=True)
    create_piece_size_C(piecename="kirin_master", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="silver_chariot")
    create_piece_size_C(piecename="silver_chariot", rotate=True)
    create_piece_size_C(piecename="silver_chariot", ispromoted=True)
    create_piece_size_C(piecename="silver_chariot", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="vertical_bear")
    create_piece_size_C(piecename="vertical_bear", rotate=True)
    create_piece_size_C(piecename="vertical_bear", ispromoted=True)
    create_piece_size_C(piecename="vertical_bear", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="pig_general")
    create_piece_size_C(piecename="pig_general", rotate=True)
    create_piece_size_C(piecename="pig_general", ispromoted=True)
    create_piece_size_C(piecename="pig_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="chicken_general")
    create_piece_size_C(piecename="chicken_general", rotate=True)
    create_piece_size_C(piecename="chicken_general", ispromoted=True)
    create_piece_size_C(piecename="chicken_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="pup_general")
    create_piece_size_C(piecename="pup_general", rotate=True)
    create_piece_size_C(piecename="pup_general", ispromoted=True)
    create_piece_size_C(piecename="pup_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="horse_general")
    create_piece_size_C(piecename="horse_general", rotate=True)
    create_piece_size_C(piecename="horse_general", ispromoted=True)
    create_piece_size_C(piecename="horse_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="ox_general")
    create_piece_size_C(piecename="ox_general", rotate=True)
    create_piece_size_C(piecename="ox_general", ispromoted=True)
    create_piece_size_C(piecename="ox_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="center_standard")
    create_piece_size_C(piecename="center_standard", rotate=True)
    create_piece_size_C(piecename="center_standard", ispromoted=True)
    create_piece_size_C(piecename="center_standard", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="side_boar")
    create_piece_size_C(piecename="side_boar", rotate=True)
    create_piece_size_C(piecename="side_boar", ispromoted=True)
    create_piece_size_C(piecename="side_boar", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="captive_cadet")
    create_piece_size_C(piecename="captive_cadet", rotate=True)
    create_piece_size_C(piecename="captive_cadet", ispromoted=True)
    create_piece_size_C(piecename="captive_cadet", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_stag")
    create_piece_size_C(piecename="great_stag", rotate=True)
    create_piece_size_C(piecename="great_stag", ispromoted=True)
    create_piece_size_C(piecename="great_stag", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="violent_dragon")
    create_piece_size_C(piecename="violent_dragon", rotate=True)
    create_piece_size_C(piecename="violent_dragon", ispromoted=True)
    create_piece_size_C(piecename="violent_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="woodland_demon")
    create_piece_size_C(piecename="woodland_demon", rotate=True)
    create_piece_size_C(piecename="woodland_demon", ispromoted=True)
    create_piece_size_C(piecename="woodland_demon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="stone_chariot")
    create_piece_size_C(piecename="stone_chariot", rotate=True)
    create_piece_size_C(piecename="stone_chariot", ispromoted=True)
    create_piece_size_C(piecename="stone_chariot", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="cloud_eagle")
    create_piece_size_C(piecename="cloud_eagle", rotate=True)
    create_piece_size_C(piecename="cloud_eagle", ispromoted=True)
    create_piece_size_C(piecename="cloud_eagle", rotate=True, ispromoted=True)
    create_piece_size_B_plus(piecename="side_wolf")
    create_piece_size_B_plus(piecename="side_wolf", rotate=True)
    create_piece_size_B_plus(piecename="side_wolf", ispromoted=True)
    create_piece_size_B_plus(piecename="side_wolf", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="flying_cat")
    create_piece_size_C(piecename="flying_cat", rotate=True)
    create_piece_size_C(piecename="flying_cat", ispromoted=True)
    create_piece_size_C(piecename="flying_cat", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="mountain_falcon")
    create_piece_size_C(piecename="mountain_falcon", rotate=True)
    create_piece_size_C(piecename="mountain_falcon", ispromoted=True)
    create_piece_size_C(piecename="mountain_falcon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="vertical_tiger")
    create_piece_size_C(piecename="vertical_tiger", rotate=True)
    create_piece_size_C(piecename="vertical_tiger", ispromoted=True)
    create_piece_size_C(piecename="vertical_tiger", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="little_standard")
    create_piece_size_C(piecename="little_standard", rotate=True)
    create_piece_size_C(piecename="little_standard", ispromoted=True)
    create_piece_size_C(piecename="little_standard", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="cloud_dragon")
    create_piece_size_C(piecename="cloud_dragon", rotate=True)
    create_piece_size_C(piecename="cloud_dragon", ispromoted=True)
    create_piece_size_C(piecename="cloud_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="copper_chariot")
    create_piece_size_C(piecename="copper_chariot", rotate=True)
    create_piece_size_C(piecename="copper_chariot", ispromoted=True)
    create_piece_size_C(piecename="copper_chariot", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="wood_chariot")
    create_piece_size_C(piecename="wood_chariot", rotate=True)
    create_piece_size_C(piecename="wood_chariot", ispromoted=True)
    create_piece_size_C(piecename="wood_chariot", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="flying_goose")
    create_piece_size_C(piecename="flying_goose", rotate=True)
    create_piece_size_C(piecename="flying_goose", ispromoted=True)
    create_piece_size_C(piecename="flying_goose", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="strutting_crow")
    create_piece_size_C(piecename="strutting_crow", rotate=True)
    create_piece_size_C(piecename="strutting_crow", ispromoted=True)
    create_piece_size_C(piecename="strutting_crow", rotate=True, ispromoted=True)
    create_piece_size_B(piecename="blind_dog")
    create_piece_size_B(piecename="blind_dog", rotate=True)
    create_piece_size_B(piecename="blind_dog", ispromoted=True)
    create_piece_size_B(piecename="blind_dog", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="water_general")
    create_piece_size_C(piecename="water_general", rotate=True)
    create_piece_size_C(piecename="water_general", ispromoted=True)
    create_piece_size_C(piecename="water_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="fire_general")
    create_piece_size_C(piecename="fire_general", rotate=True)
    create_piece_size_C(piecename="fire_general", ispromoted=True)
    create_piece_size_C(piecename="fire_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="little_turtle")
    create_piece_size_C(piecename="little_turtle", rotate=True)
    create_piece_size_C(piecename="little_turtle", ispromoted=True)
    create_piece_size_C(piecename="little_turtle", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_turtle")
    create_piece_size_C(piecename="great_turtle", rotate=True)
    create_piece_size_C(piecename="great_turtle", ispromoted=True)
    create_piece_size_C(piecename="great_turtle", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="tile_chariot")
    create_piece_size_C(piecename="tile_chariot", rotate=True)
    create_piece_size_C(piecename="tile_chariot", ispromoted=True)
    create_piece_size_C(piecename="tile_chariot", rotate=True, ispromoted=True)
    create_piece_size_B_plus(piecename="vertical_wolf")
    create_piece_size_B_plus(piecename="vertical_wolf", rotate=True)
    create_piece_size_B_plus(piecename="vertical_wolf", ispromoted=True)
    create_piece_size_B_plus(piecename="vertical_wolf", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="side_ox")
    create_piece_size_C(piecename="side_ox", rotate=True)
    create_piece_size_C(piecename="side_ox", ispromoted=True)
    create_piece_size_C(piecename="side_ox", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="liberated_horse")
    create_piece_size_C(piecename="liberated_horse", rotate=True)
    create_piece_size_C(piecename="liberated_horse", ispromoted=True)
    create_piece_size_C(piecename="liberated_horse", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="flying_cock")
    create_piece_size_C(piecename="flying_cock", rotate=True)
    create_piece_size_C(piecename="flying_cock", ispromoted=True)
    create_piece_size_C(piecename="flying_cock", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="violent_stag")
    create_piece_size_C(piecename="violent_stag", rotate=True)
    create_piece_size_C(piecename="violent_stag", ispromoted=True)
    create_piece_size_C(piecename="violent_stag", rotate=True, ispromoted=True)
    create_piece_size_B_plus(piecename="violent_wolf")
    create_piece_size_B_plus(piecename="violent_wolf", rotate=True)
    create_piece_size_B_plus(piecename="violent_wolf", ispromoted=True)
    create_piece_size_B_plus(piecename="violent_wolf", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="treacherous_fox")
    create_piece_size_C(piecename="treacherous_fox", rotate=True)
    create_piece_size_C(piecename="treacherous_fox", ispromoted=True)
    create_piece_size_C(piecename="treacherous_fox", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="center_master")
    create_piece_size_C(piecename="center_master", rotate=True)
    create_piece_size_C(piecename="center_master", ispromoted=True)
    create_piece_size_C(piecename="center_master", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="roc_master")
    create_piece_size_C(piecename="roc_master", rotate=True)
    create_piece_size_C(piecename="roc_master", ispromoted=True)
    create_piece_size_C(piecename="roc_master", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="earth_chariot")
    create_piece_size_C(piecename="earth_chariot", rotate=True)
    create_piece_size_C(piecename="earth_chariot", ispromoted=True)
    create_piece_size_C(piecename="earth_chariot", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="horseman")
    create_piece_size_C(piecename="horseman", rotate=True)
    create_piece_size_C(piecename="horseman", ispromoted=True)
    create_piece_size_C(piecename="horseman", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="swooping_owl")
    create_piece_size_C(piecename="swooping_owl", rotate=True)
    create_piece_size_C(piecename="swooping_owl", ispromoted=True)
    create_piece_size_C(piecename="swooping_owl", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="climbing_monkey")
    create_piece_size_C(piecename="climbing_monkey", rotate=True)
    create_piece_size_C(piecename="climbing_monkey", ispromoted=True)
    create_piece_size_C(piecename="climbing_monkey", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="swallows_wings")
    create_piece_size_C(piecename="swallows_wings", rotate=True)
    create_piece_size_C(piecename="swallows_wings", ispromoted=True)
    create_piece_size_C(piecename="swallows_wings", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="oxcart")
    create_piece_size_C(piecename="oxcart", rotate=True)
    create_piece_size_C(piecename="oxcart", ispromoted=True)
    create_piece_size_C(piecename="oxcart", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="wind_general")
    create_piece_size_C(piecename="wind_general", rotate=True)
    create_piece_size_C(piecename="wind_general", ispromoted=True)
    create_piece_size_C(piecename="wind_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="river_general")
    create_piece_size_C(piecename="river_general", rotate=True)
    create_piece_size_C(piecename="river_general", ispromoted=True)
    create_piece_size_C(piecename="river_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="mountain_general")
    create_piece_size_C(piecename="mountain_general", rotate=True)
    create_piece_size_C(piecename="mountain_general", ispromoted=True)
    create_piece_size_C(piecename="mountain_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="horse_soldier")
    create_piece_size_C(piecename="horse_soldier", rotate=True)
    create_piece_size_C(piecename="horse_soldier", ispromoted=True)
    create_piece_size_C(piecename="horse_soldier", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="ox_soldier")
    create_piece_size_C(piecename="ox_soldier", rotate=True)
    create_piece_size_C(piecename="ox_soldier", ispromoted=True)
    create_piece_size_C(piecename="ox_soldier", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="boar_soldier")
    create_piece_size_C(piecename="boar_soldier", rotate=True)
    create_piece_size_C(piecename="boar_soldier", ispromoted=True)
    create_piece_size_C(piecename="boar_soldier", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="leopard_soldier")
    create_piece_size_C(piecename="leopard_soldier", rotate=True)
    create_piece_size_C(piecename="leopard_soldier", ispromoted=True)
    create_piece_size_C(piecename="leopard_soldier", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="bear_soldier")
    create_piece_size_C(piecename="bear_soldier", rotate=True)
    create_piece_size_C(piecename="bear_soldier", ispromoted=True)
    create_piece_size_C(piecename="bear_soldier", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_standard")
    create_piece_size_C(piecename="great_standard", rotate=True)
    create_piece_size_C(piecename="great_standard", ispromoted=True)
    create_piece_size_C(piecename="great_standard", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_master")
    create_piece_size_C(piecename="great_master", rotate=True)
    create_piece_size_C(piecename="great_master", ispromoted=True)
    create_piece_size_C(piecename="great_master", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="side_monkey")
    create_piece_size_C(piecename="side_monkey", rotate=True)
    create_piece_size_C(piecename="side_monkey", ispromoted=True)
    create_piece_size_C(piecename="side_monkey", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="longbow_soldier")
    create_piece_size_C(piecename="longbow_soldier", rotate=True)
    create_piece_size_C(piecename="longbow_soldier", ispromoted=True)
    create_piece_size_C(piecename="longbow_soldier", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="vertical_pup")
    create_piece_size_C(piecename="vertical_pup", rotate=True)
    create_piece_size_C(piecename="vertical_pup", ispromoted=True)
    create_piece_size_C(piecename="vertical_pup", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="vertical_horse")
    create_piece_size_C(piecename="vertical_horse", rotate=True)
    create_piece_size_C(piecename="vertical_horse", ispromoted=True)
    create_piece_size_C(piecename="vertical_horse", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="burning_soldier")
    create_piece_size_C(piecename="burning_soldier", rotate=True)
    create_piece_size_C(piecename="burning_soldier", ispromoted=True)
    create_piece_size_C(piecename="burning_soldier", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="sword_soldier")
    create_piece_size_C(piecename="sword_soldier", rotate=True)
    create_piece_size_C(piecename="sword_soldier", ispromoted=True)
    create_piece_size_C(piecename="sword_soldier", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="spear_soldier")
    create_piece_size_C(piecename="spear_soldier", rotate=True)
    create_piece_size_C(piecename="spear_soldier", ispromoted=True)
    create_piece_size_C(piecename="spear_soldier", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="vertical_leopard")
    create_piece_size_C(piecename="vertical_leopard", rotate=True)
    create_piece_size_C(piecename="vertical_leopard", ispromoted=True)
    create_piece_size_C(piecename="vertical_leopard", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="crossbow_soldier")
    create_piece_size_C(piecename="crossbow_soldier", rotate=True)
    create_piece_size_C(piecename="crossbow_soldier", ispromoted=True)
    create_piece_size_C(piecename="crossbow_soldier", rotate=True, ispromoted=True)
    create_piece_size_B(piecename="roaring_dog")
    create_piece_size_B(piecename="roaring_dog", rotate=True)
    create_piece_size_B(piecename="roaring_dog", ispromoted=True)
    create_piece_size_B(piecename="roaring_dog", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="right_army", ispromoted=True)
    create_piece_size_C(piecename="right_army", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="left_army", ispromoted=True)
    create_piece_size_C(piecename="left_army", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="free_fire", ispromoted=True)
    create_piece_size_C(piecename="free_fire", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_whale", ispromoted=True)
    create_piece_size_C(piecename="great_whale", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="divine_tiger", ispromoted=True)
    create_piece_size_C(piecename="divine_tiger", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="divine_turtle", ispromoted=True)
    create_piece_size_C(piecename="divine_turtle", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="elephant_king", ispromoted=True)
    create_piece_size_C(piecename="elephant_king", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="captive_bird", ispromoted=True)
    create_piece_size_C(piecename="captive_bird", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="thunder_runner", ispromoted=True)
    create_piece_size_C(piecename="thunder_runner", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_shark", ispromoted=True)
    create_piece_size_C(piecename="great_shark", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="playful_cockatoo", ispromoted=True)
    create_piece_size_C(piecename="playful_cockatoo", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="running_dragon", ispromoted=True)
    create_piece_size_C(piecename="running_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="free_stag", ispromoted=True)
    create_piece_size_C(piecename="free_stag", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="rain_demon", ispromoted=True)
    create_piece_size_C(piecename="rain_demon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="flying_crocodile", ispromoted=True)
    create_piece_size_C(piecename="flying_crocodile", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="beast_bird", ispromoted=True)
    create_piece_size_C(piecename="beast_bird", rotate=True, ispromoted=True)
    create_piece_size_B(piecename="free_dog", ispromoted=True)
    create_piece_size_B(piecename="free_dog", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="goose_wing", ispromoted=True)
    create_piece_size_C(piecename="goose_wing", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="free_pig", ispromoted=True)
    create_piece_size_C(piecename="free_pig", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="free_chicken", ispromoted=True)
    create_piece_size_C(piecename="free_chicken", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="free_horse", ispromoted=True)
    create_piece_size_C(piecename="free_horse", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="free_ox", ispromoted=True)
    create_piece_size_C(piecename="free_ox", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="right_phoenix", ispromoted=True)
    create_piece_size_C(piecename="right_phoenix", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="walking_heron", ispromoted=True)
    create_piece_size_C(piecename="walking_heron", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="strong_eagle", ispromoted=True)
    create_piece_size_C(piecename="strong_eagle", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="cavalier", ispromoted=True)
    create_piece_size_C(piecename="cavalier", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="copper_elephant", ispromoted=True)
    create_piece_size_C(piecename="copper_elephant", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="burning_chariot", ispromoted=True)
    create_piece_size_C(piecename="burning_chariot", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="tiger_soldier", ispromoted=True)
    create_piece_size_C(piecename="tiger_soldier", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="ancient_dragon", ispromoted=True)
    create_piece_size_C(piecename="ancient_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="free_bird", ispromoted=True)
    create_piece_size_C(piecename="free_bird", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="wind_snapping_turtle", ispromoted=True)
    create_piece_size_C(piecename="wind_snapping_turtle", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_horse", ispromoted=True)
    create_piece_size_C(piecename="great_horse", rotate=True, ispromoted=True)
    create_piece_size_B(piecename="left_dog", ispromoted=True)
    create_piece_size_B(piecename="left_dog", rotate=True, ispromoted=True)
    create_piece_size_B(piecename="right_dog", ispromoted=True)
    create_piece_size_B(piecename="right_dog", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_dream_eater", ispromoted=True)
    create_piece_size_C(piecename="great_dream_eater", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="flying_falcon", ispromoted=True)
    create_piece_size_C(piecename="flying_falcon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="treasure_turtle", ispromoted=True)
    create_piece_size_C(piecename="treasure_turtle", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="spirit_turtle", ispromoted=True)
    create_piece_size_C(piecename="spirit_turtle", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="running_tile", ispromoted=True)
    create_piece_size_C(piecename="running_tile", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_bear", ispromoted=True)
    create_piece_size_C(piecename="great_bear", rotate=True, ispromoted=True)
    create_piece_size_B_plus(piecename="venomous_wolf", ispromoted=True)
    create_piece_size_B_plus(piecename="venomous_wolf", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="heavenly_horse", ispromoted=True)
    create_piece_size_C(piecename="heavenly_horse", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="raiding_falcon", ispromoted=True)
    create_piece_size_C(piecename="raiding_falcon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="rushing_boar", ispromoted=True)
    create_piece_size_C(piecename="rushing_boar", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="bears_eyes", ispromoted=True)
    create_piece_size_C(piecename="bears_eyes", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="mountain_crane", ispromoted=True)
    create_piece_size_C(piecename="mountain_crane", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="young_bird", ispromoted=True)
    create_piece_size_C(piecename="young_bird", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="divine_sparrow", ispromoted=True)
    create_piece_size_C(piecename="divine_sparrow", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="divine_dragon", ispromoted=True)
    create_piece_size_C(piecename="divine_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="gliding_swallow", ispromoted=True)
    create_piece_size_C(piecename="gliding_swallow", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="plodding_ox", ispromoted=True)
    create_piece_size_C(piecename="plodding_ox", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="bird_of_paradise", ispromoted=True)
    create_piece_size_C(piecename="bird_of_paradise", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="strong_chariot", ispromoted=True)
    create_piece_size_C(piecename="strong_chariot", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="coiled_dragon", ispromoted=True)
    create_piece_size_C(piecename="coiled_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="violent_wind", ispromoted=True)
    create_piece_size_C(piecename="violent_wind", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="chinese_river", ispromoted=True)
    create_piece_size_C(piecename="chinese_river", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="peaceful_mountain", ispromoted=True)
    create_piece_size_C(piecename="peaceful_mountain", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="running_ox", ispromoted=True)
    create_piece_size_C(piecename="running_ox", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="running_boar", ispromoted=True)
    create_piece_size_C(piecename="running_boar", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="running_leopard", ispromoted=True)
    create_piece_size_C(piecename="running_leopard", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="strong_bear", ispromoted=True)
    create_piece_size_C(piecename="strong_bear", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="right_iron_chariot", ispromoted=True)
    create_piece_size_C(piecename="right_iron_chariot", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="left_iron_chariot", ispromoted=True)
    create_piece_size_C(piecename="left_iron_chariot", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="fire_ox", ispromoted=True)
    create_piece_size_C(piecename="fire_ox", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="longbow_general", ispromoted=True)
    create_piece_size_C(piecename="longbow_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="leopard_king", ispromoted=True)
    create_piece_size_C(piecename="leopard_king", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="burning_general", ispromoted=True)
    create_piece_size_C(piecename="burning_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="sword_general", ispromoted=True)
    create_piece_size_C(piecename="sword_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_falcon", ispromoted=True)
    create_piece_size_C(piecename="great_falcon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_eagle", ispromoted=True)
    create_piece_size_C(piecename="great_eagle", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="spear_general", ispromoted=True)
    create_piece_size_C(piecename="spear_general", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_leopard", ispromoted=True)
    create_piece_size_C(piecename="great_leopard", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_tiger", ispromoted=True)
    create_piece_size_C(piecename="great_tiger", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="crossbow_general", ispromoted=True)
    create_piece_size_C(piecename="crossbow_general", rotate=True, ispromoted=True)



def add_for_tai():
    create_piece_size_B(piecename="rams_head_soldier")
    create_piece_size_B(piecename="rams_head_soldier", rotate=True)
    create_piece_size_C(piecename="peacock")
    create_piece_size_C(piecename="peacock", rotate=True)
    create_piece_size_B(piecename="soldier")
    create_piece_size_B(piecename="soldier", rotate=True)
    create_piece_size_C(piecename="side_dragon")
    create_piece_size_C(piecename="side_dragon", rotate=True)
    create_piece_size_C(piecename="vermillion_sparrow")
    create_piece_size_C(piecename="vermillion_sparrow", rotate=True)
    create_piece_size_C(piecename="golden_deer")
    create_piece_size_C(piecename="golden_deer", rotate=True)
    #TODO In Tai it's silver_hare and in Taikyoku silver_rabbit
    create_piece_size_C(piecename="silver_rabbit")
    create_piece_size_C(piecename="silver_rabbit", rotate=True)
    create_piece_size_C(piecename="fierce_eagle")
    create_piece_size_C(piecename="fierce_eagle", rotate=True)
    create_piece_size_B(piecename="turtle_snake")
    create_piece_size_B(piecename="turtle_snake", rotate=True)

    #Non-promoted pieces - in Chu we had created promoted only
    create_piece_size_B(piecename="white_horse")
    create_piece_size_B(piecename="white_horse", rotate=True)
    create_piece_size_B(piecename="whale")
    create_piece_size_B(piecename="whale", rotate=True)
    create_piece_size_B(piecename="flying_ox")
    create_piece_size_B(piecename="flying_ox", rotate=True)
    create_piece_size_C(piecename="prince")
    create_piece_size_C(piecename="prince", rotate=True)

def add_for_maka_dai_dai():
    create_piece_size_D(piecename="deva")
    create_piece_size_D(piecename="deva", rotate=True)
    create_piece_size_C(piecename="reclining_dragon")
    create_piece_size_C(piecename="reclining_dragon", rotate=True)
    create_piece_size_D(piecename="dark_spirit")
    create_piece_size_D(piecename="dark_spirit", rotate=True)
    create_piece_size_C(piecename="donkey")
    create_piece_size_C(piecename="donkey", rotate=True)
    create_piece_size_C(piecename="capricorn")
    create_piece_size_C(piecename="capricorn", rotate=True)
    create_piece_size_C(piecename="coiled_serpent")
    create_piece_size_C(piecename="coiled_serpent", rotate=True)
    create_piece_size_C(piecename="buddhist_devil")
    create_piece_size_C(piecename="buddhist_devil", rotate=True)
    create_piece_size_C(piecename="tile_general")
    create_piece_size_C(piecename="tile_general", rotate=True)
    create_piece_size_C(piecename="earth_general")
    create_piece_size_C(piecename="earth_general", rotate=True)
    create_piece_size_C(piecename="guardian_of_the_gods")
    create_piece_size_C(piecename="guardian_of_the_gods", rotate=True)
    create_piece_size_C(piecename="chinese_cock")
    create_piece_size_C(piecename="chinese_cock", rotate=True)
    create_piece_size_C(piecename="old_monkey")
    create_piece_size_C(piecename="old_monkey", rotate=True)
    create_piece_size_B_plus(piecename="blind_bear")
    create_piece_size_B_plus(piecename="blind_bear", rotate=True)
    create_piece_size_B(piecename="wrestler")
    create_piece_size_B(piecename="wrestler", rotate=True)
    create_piece_size_C(piecename="side_flier")
    create_piece_size_C(piecename="side_flier", rotate=True)

    create_piece_size_D(piecename="emperor")
    create_piece_size_D(piecename="emperor", rotate=True)
    create_piece_size_D(piecename="teaching_king")
    create_piece_size_D(piecename="teaching_king", rotate=True)
    create_piece_size_D(piecename="buddhist_spirit")
    create_piece_size_D(piecename="buddhist_spirit", rotate=True)
    create_piece_size_C(piecename="bat")
    create_piece_size_C(piecename="bat", rotate=True)
    create_piece_size_C(piecename="free_tile")
    create_piece_size_C(piecename="free_tile", rotate=True)
    create_piece_size_C(piecename="free_serpent")
    create_piece_size_C(piecename="free_serpent", rotate=True)
    create_piece_size_C(piecename="free_cat")
    create_piece_size_C(piecename="free_cat", rotate=True)
    create_piece_size_B_plus(piecename="free_bear")
    create_piece_size_B_plus(piecename="free_bear", rotate=True)
    create_piece_size_C(piecename="free_copper")
    create_piece_size_C(piecename="free_copper", rotate=True)
    create_piece_size_C(piecename="free_dragon")
    create_piece_size_C(piecename="free_dragon", rotate=True)
    create_piece_size_C(piecename="free_earth")
    create_piece_size_C(piecename="free_earth", rotate=True)
    create_piece_size_C(piecename="free_gold")
    create_piece_size_C(piecename="free_gold", rotate=True)
    create_piece_size_C(piecename="free_iron")
    create_piece_size_C(piecename="free_iron", rotate=True)
    create_piece_size_C(piecename="free_leopard")
    create_piece_size_C(piecename="free_leopard", rotate=True)
    create_piece_size_C(piecename="free_goer")
    create_piece_size_C(piecename="free_goer", rotate=True)
    create_piece_size_C(piecename="free_stone")
    create_piece_size_C(piecename="free_stone", rotate=True)
    create_piece_size_C(piecename="free_silver")
    create_piece_size_C(piecename="free_silver", rotate=True)
    create_piece_size_C(piecename="free_tiger")
    create_piece_size_C(piecename="free_tiger", rotate=True)
    create_piece_size_C(piecename="free_wolf")
    create_piece_size_C(piecename="free_wolf", rotate=True)


def add_for_dai_dai():
    create_piece_size_B(piecename="right_chariot")
    create_piece_size_B(piecename="right_chariot", rotate=True)
    create_piece_size_B(piecename="blue_dragon")
    create_piece_size_B(piecename="blue_dragon", rotate=True)
    #TODO Properly handle issue with font and 1st kanji Howling Dog
    create_piece_size_B_plus(piecename="howling_dog")
    create_piece_size_B_plus(piecename="howling_dog", rotate=True)
    create_piece_size_B(piecename="left_chariot")
    create_piece_size_B(piecename="left_chariot", rotate=True)
    create_piece_size_B(piecename="white_tiger")
    create_piece_size_B(piecename="white_tiger", rotate=True)

    create_piece_size_C(piecename="golden_bird")
    create_piece_size_C(piecename="golden_bird", rotate=True)
    create_piece_size_C(piecename="free_demon")
    create_piece_size_C(piecename="free_demon", rotate=True)
    create_piece_size_C(piecename="free_dream_eater")
    create_piece_size_C(piecename="free_dream_eater", rotate=True)
    create_piece_size_C(piecename="eastern_barbarian")
    create_piece_size_C(piecename="eastern_barbarian", rotate=True)
    create_piece_size_C(piecename="long_nosed_goblin")
    create_piece_size_C(piecename="long_nosed_goblin", rotate=True)
    create_piece_size_C(piecename="racing_chariot")
    create_piece_size_C(piecename="racing_chariot", rotate=True)
    create_piece_size_C(piecename="square_mover")
    create_piece_size_C(piecename="square_mover", rotate=True)
    create_piece_size_C(piecename="western_barbarian")
    create_piece_size_C(piecename="western_barbarian", rotate=True)
    create_piece_size_C(piecename="great_dragon")
    create_piece_size_C(piecename="great_dragon", rotate=True)
    create_piece_size_C(piecename="prancing_stag")
    create_piece_size_C(piecename="prancing_stag", rotate=True)
    create_piece_size_C(piecename="savage_tiger")
    create_piece_size_C(piecename="savage_tiger", rotate=True)
    create_piece_size_C(piecename="fragrant_elephant")
    create_piece_size_C(piecename="fragrant_elephant", rotate=True)
    create_piece_size_C(piecename="right_general")
    create_piece_size_C(piecename="right_general", rotate=True)
    create_piece_size_C(piecename="standard_bearer")
    create_piece_size_C(piecename="standard_bearer", rotate=True)
    create_piece_size_C(piecename="blind_monkey")
    create_piece_size_C(piecename="blind_monkey", rotate=True)
    #TODO in Taikyoku it's wooden_dove but in other variants it's just Dove
    create_piece_size_C(piecename="wooden_dove")
    create_piece_size_C(piecename="wooden_dove", rotate=True)
    create_piece_size_C(piecename="enchanted_badger")
    create_piece_size_C(piecename="enchanted_badger", rotate=True)
    create_piece_size_C(piecename="enchanted_fox")
    create_piece_size_C(piecename="enchanted_fox", rotate=True)
    create_piece_size_C(piecename="flying_horse")
    create_piece_size_C(piecename="flying_horse", rotate=True)
    create_piece_size_C(piecename="furious_fiend", ispromoted=True)
    create_piece_size_C(piecename="furious_fiend", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_elephant", ispromoted=True)
    create_piece_size_C(piecename="great_elephant", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="hook_mover")
    create_piece_size_C(piecename="hook_mover", rotate=True)
    create_piece_size_C(piecename="left_general")
    create_piece_size_C(piecename="left_general", rotate=True)
    create_piece_size_C(piecename="lion_dog")
    create_piece_size_C(piecename="lion_dog", rotate=True)
    create_piece_size_C(piecename="mountain_witch", ispromoted=True)
    create_piece_size_C(piecename="mountain_witch", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="neighboring_king")
    create_piece_size_C(piecename="neighboring_king", rotate=True)
    create_piece_size_C(piecename="northern_barbarian")
    create_piece_size_C(piecename="northern_barbarian", rotate=True)
    create_piece_size_C(piecename="old_kite")
    create_piece_size_C(piecename="old_kite", rotate=True)
    create_piece_size_C(piecename="old_rat")
    create_piece_size_C(piecename="old_rat", rotate=True)
    create_piece_size_C(piecename="poisonous_snake")
    create_piece_size_C(piecename="poisonous_snake", rotate=True)
    create_piece_size_C(piecename="rushing_bird")
    create_piece_size_C(piecename="rushing_bird", rotate=True)
    create_piece_size_C(piecename="she_devil")
    create_piece_size_C(piecename="she_devil", rotate=True)
    create_piece_size_C(piecename="southern_barbarian")
    create_piece_size_C(piecename="southern_barbarian", rotate=True)
    create_piece_size_C(piecename="violent_bear")
    create_piece_size_C(piecename="violent_bear", rotate=True)
    create_piece_size_C(piecename="white_elephant")
    create_piece_size_C(piecename="white_elephant", rotate=True)
    create_piece_size_C(piecename="wizard_stork", ispromoted=True)
    create_piece_size_C(piecename="wizard_stork", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="wood_general")
    create_piece_size_C(piecename="wood_general", rotate=True)

    create_piece_size_C(piecename="free_dream_eater", ispromoted=True)
    create_piece_size_C(piecename="free_dream_eater", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="lion_dog", ispromoted=True)
    create_piece_size_C(piecename="lion_dog", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="white_elephant", ispromoted=True)
    create_piece_size_C(piecename="white_elephant", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="free_demon", ispromoted=True)
    create_piece_size_C(piecename="free_demon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="square_mover", ispromoted=True)
    create_piece_size_C(piecename="square_mover", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="hook_mover", ispromoted=True)
    create_piece_size_C(piecename="hook_mover", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="golden_bird", ispromoted=True)
    create_piece_size_C(piecename="golden_bird", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="long_nosed_goblin", ispromoted=True)
    create_piece_size_C(piecename="long_nosed_goblin", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="fragrant_elephant", ispromoted=True)
    create_piece_size_C(piecename="fragrant_elephant", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="standard_bearer", ispromoted=True)
    create_piece_size_C(piecename="standard_bearer", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="great_dragon", ispromoted=True)
    create_piece_size_C(piecename="great_dragon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="she_devil", ispromoted=True)
    create_piece_size_C(piecename="she_devil", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="wooden_dove", ispromoted=True)
    create_piece_size_C(piecename="wooden_dove", rotate=True, ispromoted=True)


def add_for_dai():
    create_piece_size_C(piecename="angry_boar")
    create_piece_size_C(piecename="angry_boar", rotate=True)
    create_piece_size_C(piecename="cat_sword")
    create_piece_size_C(piecename="cat_sword", rotate=True)
    create_piece_size_C(piecename="evil_wolf")
    create_piece_size_C(piecename="evil_wolf", rotate=True)
    create_piece_size_C(piecename="flying_dragon")
    create_piece_size_C(piecename="flying_dragon", rotate=True)
    create_piece_size_C(piecename="stone_general")
    create_piece_size_C(piecename="stone_general", rotate=True)
    create_piece_size_C(piecename="violent_ox")
    create_piece_size_C(piecename="violent_ox", rotate=True)
    create_piece_size_C(piecename="gold_general", ispromoted=True)
    create_piece_size_C(piecename="gold_general", rotate=True, ispromoted=True)

def add_for_tenjiku():
    create_piece_size_A_tokinstyle(piecename="dog")
    create_piece_size_A_tokinstyle(piecename="dog", rotate=True)
    create_piece_size_B_plus(piecename="side_soldier")
    create_piece_size_B_plus(piecename="side_soldier", rotate=True)
    create_piece_size_B_plus(piecename="vertical_soldier")
    create_piece_size_B_plus(piecename="vertical_soldier", rotate=True)
    create_piece_size_C(piecename="chariot_soldier")
    create_piece_size_C(piecename="chariot_soldier", rotate=True)
    create_piece_size_C(piecename="knight")
    create_piece_size_C(piecename="knight", rotate=True)
    create_piece_size_C(piecename="iron_general")
    create_piece_size_C(piecename="iron_general", rotate=True)
    create_piece_size_C(piecename="horned_falcon")
    create_piece_size_C(piecename="horned_falcon", rotate=True)
    create_piece_size_C(piecename="soaring_eagle")
    create_piece_size_C(piecename="soaring_eagle", rotate=True)
    create_piece_size_C(piecename="water_buffalo")
    create_piece_size_C(piecename="water_buffalo", rotate=True)
    create_piece_size_C(piecename="bishop_general")
    create_piece_size_C(piecename="bishop_general", rotate=True)
    create_piece_size_C(piecename="rook_general")
    create_piece_size_C(piecename="rook_general", rotate=True)
    create_piece_size_C(piecename="vice_general")
    create_piece_size_C(piecename="vice_general", rotate=True)
    create_piece_size_C(piecename="great_general")
    create_piece_size_C(piecename="great_general", rotate=True)
    create_piece_size_C(piecename="fire_demon")
    create_piece_size_C(piecename="fire_demon", rotate=True)
    create_piece_size_C(piecename="lion_hawk")
    create_piece_size_C(piecename="lion_hawk", rotate=True)
    create_piece_size_C(piecename="free_eagle")
    create_piece_size_C(piecename="free_eagle", rotate=True)

    create_piece_size_A(piecename="multi_general", ispromoted=True)
    create_piece_size_A(piecename="multi_general", ispromoted=True, rotate=True)
    create_piece_size_B_plus(piecename="chariot_soldier", ispromoted=True)
    create_piece_size_B_plus(piecename="chariot_soldier", ispromoted=True, rotate=True)
    create_piece_size_B_plus(piecename="water_buffalo", ispromoted=True)
    create_piece_size_B_plus(piecename="water_buffalo", ispromoted=True, rotate=True)
    create_piece_size_C(piecename="bishop_general", ispromoted=True)
    create_piece_size_C(piecename="bishop_general", ispromoted=True, rotate=True)
    create_piece_size_C(piecename="fire_demon", ispromoted=True)
    create_piece_size_C(piecename="fire_demon", ispromoted=True, rotate=True)
    create_piece_size_C(piecename="great_general", ispromoted=True)
    create_piece_size_C(piecename="great_general", ispromoted=True, rotate=True)
    create_piece_size_C(piecename="heavenly_tetrarch", ispromoted=True)
    create_piece_size_C(piecename="heavenly_tetrarch", ispromoted=True, rotate=True)
    create_piece_size_C(piecename="lion_hawk", ispromoted=True)
    create_piece_size_C(piecename="lion_hawk", ispromoted=True, rotate=True)
    create_piece_size_C(piecename="rook_general", ispromoted=True)
    create_piece_size_C(piecename="rook_general", ispromoted=True, rotate=True)
    create_piece_size_C(piecename="side_soldier", ispromoted=True)
    create_piece_size_C(piecename="side_soldier", ispromoted=True, rotate=True)
    create_piece_size_C(piecename="vertical_soldier", ispromoted=True)
    create_piece_size_C(piecename="vertical_soldier", ispromoted=True, rotate=True)
    create_piece_size_C(piecename="vice_general", ispromoted=True)
    create_piece_size_C(piecename="vice_general", ispromoted=True, rotate=True)
    create_piece_size_D(piecename="free_eagle", ispromoted=True)
    create_piece_size_D(piecename="free_eagle", ispromoted=True, rotate=True)

def create_complete_chu_set():
    create_piece_size_B(piecename="lance")
    create_piece_size_B(piecename="lance", rotate=True)
    create_piece_size_B(piecename="reverse_chariot")
    create_piece_size_B(piecename="reverse_chariot", rotate=True)
    create_piece_size_B(piecename="side_mover")
    create_piece_size_C(piecename="side_mover", ispromoted=True)
    create_piece_size_B(piecename="side_mover", rotate=True)
    create_piece_size_C(piecename="side_mover", rotate=True, ispromoted=True)
    create_piece_size_B_plus(piecename="ferocious_leopard")
    create_piece_size_B_plus(piecename="ferocious_leopard", rotate=True)
    create_piece_size_B(piecename="vertical_mover")
    create_piece_size_C(piecename="vertical_mover", ispromoted=True)
    create_piece_size_B(piecename="vertical_mover", rotate=True)
    create_piece_size_C(piecename="vertical_mover", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="copper_general")
    create_piece_size_C(piecename="copper_general", rotate=True)
    create_piece_size_C(piecename="bishop")
    create_piece_size_B_plus(piecename="bishop", ispromoted=True)
    create_piece_size_C(piecename="bishop", rotate=True)
    create_piece_size_B_plus(piecename="bishop", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="rook")
    create_piece_size_C(piecename="rook", ispromoted=True)
    create_piece_size_C(piecename="rook", rotate=True)
    create_piece_size_C(piecename="rook", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="silver_general")
    create_piece_size_C(piecename="silver_general", rotate=True)
    create_piece_size_C(piecename="dragon_horse")
    create_piece_size_C(piecename="dragon_horse", ispromoted=True)
    create_piece_size_C(piecename="dragon_horse", rotate=True)
    create_piece_size_C(piecename="dragon_horse", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="gold_general")
    create_piece_size_C(piecename="gold_general", rotate=True)
    create_piece_size_B_plus(piecename="blind_tiger")
    create_piece_size_B_plus(piecename="blind_tiger", rotate=True)
    create_piece_size_C(piecename="dragon_king")
    create_piece_size_C(piecename="dragon_king", ispromoted=True)
    create_piece_size_C(piecename="dragon_king", rotate=True)
    create_piece_size_C(piecename="dragon_king", rotate=True, ispromoted=True)
    create_piece_size_D(piecename="king_sente")
    create_piece_size_D(piecename="king_gote", rotate=True)
    create_piece_size_C(piecename="kirin")
    create_piece_size_C(piecename="kirin", rotate=True)
    create_piece_size_C(piecename="lion")
    create_piece_size_C(piecename="lion", ispromoted=True)
    create_piece_size_C(piecename="lion", rotate=True)
    create_piece_size_C(piecename="lion", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="drunk_elephant")
    create_piece_size_A(piecename="drunk_elephant", ispromoted=True)
    create_piece_size_C(piecename="drunk_elephant", rotate=True)
    create_piece_size_A(piecename="drunk_elephant", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="phoenix")
    create_piece_size_C(piecename="phoenix", rotate=True)
    create_piece_size_D(piecename="queen")
    create_piece_size_C(piecename="queen", ispromoted=True)
    create_piece_size_D(piecename="queen", rotate=True)
    create_piece_size_C(piecename="queen", rotate=True, ispromoted=True)
    create_piece_size_A(piecename="pawn")
    create_piece_size_A(piecename="pawn", rotate=True)
    create_piece_size_A(piecename="go_between")
    create_piece_size_A(piecename="go_between", rotate=True)
    create_piece_size_A_tokinstyle(piecename="tokin", ispromoted=True)
    create_piece_size_A_tokinstyle(piecename="tokin", rotate=True, ispromoted=True)
    create_piece_size_B(piecename="flying_ox", ispromoted=True)
    create_piece_size_B_plus(piecename="flying_stag", ispromoted=True)
    create_piece_size_B(piecename="free_boar", ispromoted=True)
    create_piece_size_C(piecename="horned_falcon", ispromoted=True)
    create_piece_size_C(piecename="prince", ispromoted=True)
    create_piece_size_C(piecename="soaring_eagle", ispromoted=True)
    create_piece_size_B(piecename="whale", ispromoted=True)
    create_piece_size_B(piecename="white_horse", ispromoted=True)

    create_piece_size_B(piecename="flying_ox", rotate=True, ispromoted=True)
    create_piece_size_B_plus(piecename="flying_stag", rotate=True, ispromoted=True)
    create_piece_size_B(piecename="free_boar", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="horned_falcon", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="prince", rotate=True, ispromoted=True)
    create_piece_size_C(piecename="soaring_eagle", rotate=True, ispromoted=True)
    create_piece_size_B(piecename="whale", rotate=True, ispromoted=True)
    create_piece_size_B(piecename="white_horse", rotate=True, ispromoted=True)

def create_vacant_notfound_tiles():
    new_img_vacant, new_img_notfound = MyChuPieceMaker.create_vacant_notfound_tiles()
    MyChuPieceMaker.save_image(new_img_vacant, f"{outputpath}vacant.png")
    MyChuPieceMaker.save_image(new_img_notfound, f"{outputpath}_notfound.png")

MyChuPieceMaker = ChuPieceMaker()

#MyChuPieceMaker.load_dimensions(".\\input\\dimensions_542_590.json")
#MyChuPieceMaker.load_dimensions(".\\input\\dimensions_542_590_single_kanji.json")

outputpath = ".\\output_set1\\"
MyChuPieceMaker.load_dimensions(".\\input\\dimensions_180_196_single_kanji.json")
print(f"Loaded dimension data for tiletypes {[item['tiletypename'] for item in MyChuPieceMaker.dimension_data['tiletypes']]}")
MyChuPieceMaker.load_kanji(".\\kanji\\kanji.json")
print(f"Loaded kanji for {len(MyChuPieceMaker.kanji_data)} pieces")
myimage = MyChuPieceMaker.load_image(f".\\input\\shogipiecetemplate.png")
print(f"Loaded template image with width {myimage.width} height {myimage.height}")
myimage = MyChuPieceMaker.fill_from_point(myimage, 266, 248, MyChuPieceMaker.piececolor)
MyChuPieceMaker.mycolouredtemplate = MyChuPieceMaker.fill_from_point(myimage, 4, 4, MyChuPieceMaker.boardcolor)
print("We have created the coloured template")
create_vacant_notfound_tiles()
create_complete_chu_set()
add_for_tenjiku()
add_for_dai()
add_for_dai_dai()
add_for_maka_dai_dai()
add_for_tai()
#When arriving at Taikyoku, the single kanji become too problematic
#add_for_taikyoku()
print("We have created the image files")


outputpath = ".\\output_set2\\"
MyChuPieceMaker.load_dimensions(".\\input\\dimensions_180_196.json")
print(f"Loaded dimension data for tiletypes {[item['tiletypename'] for item in MyChuPieceMaker.dimension_data['tiletypes']]}")
MyChuPieceMaker.load_kanji(".\\kanji\\kanji.json")
print(f"Loaded kanji for {len(MyChuPieceMaker.kanji_data)} pieces")
myimage = MyChuPieceMaker.load_image(f".\\input\\shogipiecetemplate.png")
print(f"Loaded template image with width {myimage.width} height {myimage.height}")
myimage = MyChuPieceMaker.fill_from_point(myimage, 266, 248, MyChuPieceMaker.piececolor)
MyChuPieceMaker.mycolouredtemplate = MyChuPieceMaker.fill_from_point(myimage, 4, 4, MyChuPieceMaker.boardcolor)
print("We have created the coloured template")
create_vacant_notfound_tiles()
create_complete_chu_set()
add_for_tenjiku()
add_for_dai()
add_for_dai_dai()
add_for_maka_dai_dai()
add_for_tai()
add_for_taikyoku()
print("We have created the image files")
